name: Package

on:
  release:
    types: [created]

jobs:
  package:
    name: Package
    runs-on: ubuntu-20.04

    steps:
    - name: Package | Checkout
      uses: actions/checkout@v2.3.4

    - name: Package | Release
      id: release
      uses: tenhaus/get-release-or-tag@v2

    - name: Package | Setup
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - name: Package | Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        PROJECT_FILE_PATH: src/AppAny.Quartz.EntityFrameworkCore.Migrations/AppAny.Quartz.EntityFrameworkCore.Migrations.csproj
        VERSION_STATIC: ${{ steps.release.outputs.tag }}
        TAG_FORMAT: '*'
        INCLUDE_SYMBOLS: true

    - name: Package | Publish | PostgreSQL
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        PROJECT_FILE_PATH: src/AppAny.Quartz.EntityFrameworkCore.Migrations.PostgreSQL/AppAny.Quartz.EntityFrameworkCore.Migrations.PostgreSQL.csproj
        VERSION_STATIC: ${{ steps.release.outputs.tag }}
        TAG_FORMAT: '*'
        INCLUDE_SYMBOLS: true
