name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Tests | Checkout
        uses: actions/checkout@v2

      - name: Tests | Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          dotnet-quality: 'preview'

      - name: Tests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

      - name: Tests | Coverage
        uses: codecov/codecov-action@v1
        with:
          files: tests/AppAny.Quartz.EntityFrameworkCore.Migrations.Tests/coverage.info
