name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    services:
      postgres:
        image: postgres:13.1
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      sqlserver:
        image: mcr.microsoft.com/azure-sql-edge:latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Test12@.

    steps:
      - name: Tests | Checkout
        uses: actions/checkout@v2

      - name: Tests | Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

      - name: Tests | Coverage
        uses: codecov/codecov-action@v1
        with:
          files: tests/AppAny.Quartz.EntityFrameworkCore.Migrations.Tests/coverage.info
