name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: Tests (Quartz ${{ matrix.quartz-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        quartz-version: [3.21.0, 4.0.1]

    steps:
      - name: Tests | Checkout
        uses: actions/checkout@v2

      - name: Tests | Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            9.0.x
            8.0.x
            10.0.x

      - name: Tests
        run: dotnet test --framework net10.0 -p:QuartzVersion=${{ matrix.quartz-version }} /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

      - name: Tests | Coverage
        uses: codecov/codecov-action@v1
        with:
          files: tests/AppAny.Quartz.EntityFrameworkCore.Migrations.Tests/coverage.info
