name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    services:
      postgres:
        image: postgres:13.1
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test

    steps:
    - name: Tests | Checkout
      uses: actions/checkout@v2

    - name: Tests | Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=coverage/ /p:CoverletOutputFormat=lcov

    - name: Tests | Coverage
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: tests/AppAny.Quartz.EntityFrameworkCore.Migrations.Tests/coverage/coverage.info
